#!/usr/bin/env ruby

class CodeCompletion
  def initialize(command)
    @command = command
  end

  def matches
    directories.select do |task|
      task[0, typed.length] == typed
    end
  end

  def typed
    @command[/\s(.+?)$/, 1] || ''
  end

  def directories
    `ls ~/Code/`.split
  end
end

puts CodeCompletion.new(ENV["COMP_LINE"]).matches
exit 0
